language: android
jdk: oraclejdk8
sudo: required

before_install:
  - chmod +x gradlew

android:
    components:
      - tools
      - platform-tools
      - extra-android-support
      - extra-google-google_play_services
      - extra-android-m2repository
      - extra-google-m2repository
      - build-tools-25.0.0
      - android-25

script: "./gradlew build --stacktrace"